# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Fenway Garden Society' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SideMenu', '~> 2.1.4'
  pod 'GoogleAPIClient/Calendar', '~> 1.0.2'
  pod 'GTMOAuth2', '~> 1.1.0'

  # Pods for Fenway Garden Society

  target 'Fenway Garden SocietyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Fenway Garden SocietyUITests' do
    inherit! :search_paths
    # Pods for testing
  end


end
