# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Fenway Garden Society' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SideMenu', '~> 2.1.4'
  #pod 'GoogleAPIClient/Calendar', '~> 1.0.2'
  pod 'FSCalendar', '~> 2.7.4'
  #pod 'GoogleAPIClientForREST', '~> 1.2.1'
  #pod 'GTMAppAuth', '~> 0.5.0'
  pod 'SwiftyJSON', '~> 3.1.4'
  pod 'Alamofire', '~> 4.4'

  # Pods for Fenway Garden Society

  target 'Fenway Garden SocietyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Fenway Garden SocietyUITests' do
    inherit! :search_paths
    # Pods for testing
  end


end
